def maikeLetra1(self, pos):
  self.setpos(pos)
  self.left(75) 
  self.forward(50) 
  self.left(30)
  self.back(30)
  self.right(30)
  self.forward(30)
  self.left(32)
  self.back(50)
  self.penup()
  self.home()

def maikeLetra2(self, pos):
  self.setpos(pos)
  self.left(75)
  self.pendown()
  self.forward(50)
  self.left(30)
  self.back(30)
  posicao = self.pos()
  self.left(75)
  self.forward(15)
  self.penup()
  self.setpos(posicao)
  self.right(75)
  self.pendown()
  self.back(20)
  self.penup()
  self.home()
  

def maikeLetra3(self, pos):
  self.setpos(pos)
  self.left(90)
  self.pendown()
  self.forward(30)
  self.penup()
  self.forward(13)
  self.right(90)
  self.forward(3)
  self.left(90)
  self.pendown()
  self.circle(4)
  self.penup()
  self.home()

def maikeLetra4(self,pos):
  self.setpos(pos)
  self.left(90)
  self.pendown()
  self.forward(50)
  self.back(30)
  self.right(55)
  self.forward(35)
  self.back(35)
  self.left(110)
  self.back(35)
  self.penup()
  self.home()

def maikeLetra5(self,pos):
  self.setpos(pos)
  self.left(90)
  self.pendown()
  self.forward(45)
  self.back(40)
  for x in range(1, 4):
    self.right(90)
    self.forward(30)
    self.back(30)
    self.left(90)
    if x == 3:
      self.penup()
      self.home()
    else:
      self.forward(20)
