def sair(self):
    self.setpos(0, 65)
    self.right(90)
    fonte = ("Comic Sans", 20, "italic")
    fonte2 = ("Comic Sans", 30, "bold")
    fonte3 = ("Comic Sans", 20, "normal")
    self.write("PEOO", False, "center", fonte2)
    self.forward(50)
    self.write("Dupla:", False, "center", fonte)
    self.forward(50)
    self.write("Maike Rosa da Silva", False, "center", fonte3)
    self.forward(50)
    self.write("Fellipe Patrick Lima de Brito", False, "center", fonte3)
    self.forward(50)

    self.setpos(-260, -110)
    self.speed(100)
    self.fillcolor("red")
    for x in range(13):
      self.begin_fill()
      self.pendown()
      self.circle(20)
      self.left(90)
      self.penup()
      self.forward(40)
      self.right(90)
      self.end_fill()
    self.left(180)
    for x in range(6):
      self.begin_fill()
      self.penup()
      self.forward(40)
      self.pendown()
      self.circle(20)
      self.end_fill()
    for x in range(12):
      self.begin_fill()
      self.penup()
      self.left(90)
      self.forward(40)
      self.right(90)
      self.pendown()
      self.circle(20)
      self.end_fill()
    self.penup()
    self.left(90)
    self.forward(41)
    self.left(90)
    for x in range(5):
      self.begin_fill()
      self.penup()
      self.forward(40)
      self.pendown()
      self.circle(20)
      self.end_fill()
    self.penup()
    self.setpos(-260, -140)
    
    
      